x = int(1)
try:
	print(x)
except:
	print("An exception occurred") 

